"""empty message

Revision ID: 71399bbf2607
Revises: 
Create Date: 2018-11-09 16:54:47.152000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71399bbf2607'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('passwordHash', sa.String(length=120), nullable=False),
    sa.Column('salt', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('group', sa.String(length=4294000000L), nullable=True),
    sa.ForeignKeyConstraint(['group'], ['group.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('password', table_name='user')
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_index('username', 'user', ['username'], unique=True)
    op.create_index('password', 'user', ['password'], unique=True)
    op.drop_table('page')
    op.drop_table('group')
    # ### end Alembic commands ###
