"""empty message

Revision ID: 9743bc22e687
Revises: eb77214f5356
Create Date: 2018-11-10 13:05:20.969712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9743bc22e687'
down_revision = 'eb77214f5356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'salt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('salt', mysql.VARCHAR(length=256), nullable=False))
    # ### end Alembic commands ###
