"""empty message

Revision ID: 1ba38c16caec
Revises: 782a18aaae4d
Create Date: 2018-11-15 12:34:54.689938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ba38c16caec'
down_revision = '782a18aaae4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'group', 'class', ['class_id'], ['id'])
    op.drop_column('group', 'class_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('class_name', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'group', type_='foreignkey')
    # ### end Alembic commands ###
