"""empty message

Revision ID: 23ec3edd76e5
Revises: b429572df7aa
Create Date: 2018-11-14 15:46:10.121099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ec3edd76e5'
down_revision = 'b429572df7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('class_name', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'group', 'class', ['class_name'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'class_name')
    # ### end Alembic commands ###
