"""empty message

Revision ID: 24649028dcf3
Revises: ef1c115b6195
Create Date: 2018-11-19 13:21:37.304152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24649028dcf3'
down_revision = 'ef1c115b6195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'group', 'class', ['class_id'], ['id'])
    op.add_column('page', sa.Column('main', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'main')
    op.drop_constraint(None, 'group', type_='foreignkey')
    # ### end Alembic commands ###
