"""empty message

Revision ID: 2f2c43b6e9b4
Revises: e32474d54b3b
Create Date: 2018-11-19 14:31:05.307072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2c43b6e9b4'
down_revision = 'e32474d54b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('main', sa.Boolean(), nullable=True))
    op.add_column('page', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'name')
    op.drop_column('page', 'main')
    # ### end Alembic commands ###
