"""empty message

Revision ID: 337370a53741
Revises: 037d4c7fbf76
Create Date: 2018-11-10 15:24:56.130599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337370a53741'
down_revision = '037d4c7fbf76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('blabla', sa.String(length=111111), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'blabla')
    # ### end Alembic commands ###
