"""empty message

Revision ID: 544349453426
Revises: 71399bbf2607
Create Date: 2018-11-09 16:56:48.013000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544349453426'
down_revision = '71399bbf2607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('passwordHash', sa.String(length=120), nullable=False),
    sa.Column('salt', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page')
    op.drop_table('group')
    # ### end Alembic commands ###
