"""empty message

Revision ID: 8c2a28d817d7
Revises: ae58dac62d86
Create Date: 2018-11-10 15:25:29.162616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2a28d817d7'
down_revision = 'ae58dac62d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('admin', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'admin')
    # ### end Alembic commands ###
