"""empty message

Revision ID: 9e8414ae6421
Revises: 1ba38c16caec
Create Date: 2018-11-15 12:42:34.933136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8414ae6421'
down_revision = '1ba38c16caec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('deadline', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'group', 'class', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('class', 'deadline')
    # ### end Alembic commands ###
