"""empty message

Revision ID: ad870f2bdf2a
Revises: 24649028dcf3
Create Date: 2018-11-19 13:52:21.960555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad870f2bdf2a'
down_revision = '24649028dcf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'group', 'class', ['class_id'], ['id'])
    op.add_column('page', sa.Column('main', sa.Boolean(), nullable=True))
    op.add_column('page', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'name')
    op.drop_column('page', 'main')
    op.drop_constraint(None, 'group', type_='foreignkey')
    # ### end Alembic commands ###
