"""empty message

Revision ID: ae58dac62d86
Revises: 337370a53741
Create Date: 2018-11-10 15:25:21.102587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae58dac62d86'
down_revision = '337370a53741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('admin', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'admin')
    # ### end Alembic commands ###
