"""empty message

Revision ID: e32474d54b3b
Revises: ad870f2bdf2a
Create Date: 2018-11-19 14:29:31.045208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e32474d54b3b'
down_revision = 'ad870f2bdf2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'group', 'class', ['class_id'], ['id'])
    op.add_column('page', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'page_ibfk_1', 'page', type_='foreignkey')
    op.create_foreign_key(None, 'page', 'group', ['group_id'], ['id'])
    op.drop_column('page', 'group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('group', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'page', type_='foreignkey')
    op.create_foreign_key(u'page_ibfk_1', 'page', 'group', ['group'], ['id'])
    op.drop_column('page', 'group_id')
    op.drop_constraint(None, 'group', type_='foreignkey')
    # ### end Alembic commands ###
