"""empty message

Revision ID: eb77214f5356
Revises: 544349453426
Create Date: 2018-11-09 16:57:23.497000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb77214f5356'
down_revision = '544349453426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('password_hash', sa.String(length=120), nullable=False))
    op.drop_column('group', 'passwordHash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('passwordHash', mysql.VARCHAR(length=120), nullable=False))
    op.drop_column('group', 'password_hash')
    # ### end Alembic commands ###
