"""empty message

Revision ID: eebe5279919f
Revises: 2f2c43b6e9b4
Create Date: 2018-11-19 14:33:54.714290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eebe5279919f'
down_revision = '2f2c43b6e9b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('is_main', sa.Boolean(), nullable=True))
    op.add_column('page', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_column('page', 'main')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('main', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('page', 'name')
    op.drop_column('page', 'is_main')
    # ### end Alembic commands ###
